# Simulation-only joint limits, mirrors joint_limits.yaml with group_1_ names.
default_velocity_scaling_factor: 0.1
default_acceleration_scaling_factor: 0.1

joint_limits:
  group_1_joint_1:
    has_velocity_limits: true
    max_velocity: 2.2689280275926285
    has_acceleration_limits: true
    max_acceleration: 0.2
  group_1_joint_2:
    has_velocity_limits: true
    max_velocity: 2.2689280275926285
    has_acceleration_limits: true
    max_acceleration: 0.2
  group_1_joint_3:
    has_velocity_limits: true
    max_velocity: 3.1415926535897931
    has_acceleration_limits: true
    max_acceleration: 0.2
  group_1_joint_4:
    has_velocity_limits: true
    max_velocity: 3.1415926535897931
    has_acceleration_limits: true
    max_acceleration: 0.2
  group_1_joint_5:
    has_velocity_limits: true
    max_velocity: 4.3633231299858242
    has_acceleration_limits: true
    max_acceleration: 0.2
  group_1_joint_6:
    has_velocity_limits: true
    max_velocity: 4.3633231299858242
    has_acceleration_limits: true
    max_acceleration: 0.2
